const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
// Export the EXACT fixed speaking-review fixtures from the original speakingReviewView().
// These are demo answers + fixed example scores; they are NOT produced by real grading and
// must never be regenerated by an actual grader. We run the original source in a Node vm so
// the strings (criteria, weak points, per-question items, Part 3 rounds, examiner overall,
// cue-card points) come out byte-for-byte identical to app.js.
const root=path.resolve(__dirname,'..');
const s=fs.readFileSync(path.join(root,'../surgo-mobile-new/app.js'),'utf8');
const fnStart=s.indexOf('function speakingReviewView(){');
if(fnStart<0)throw new Error('speakingReviewView not found in source');
// Data definitions run from `const score='6.5';` up to (but not including) `const curItems=`.
const dataStart=s.indexOf('  const score=',fnStart);
const dataEnd=s.indexOf('  const curItems=',fnStart);
const dataBlock=s.slice(dataStart,dataEnd);
// cuePoints is declared later in the function; grab just that array literal.
const cueStart=s.indexOf('  const cuePoints=[',fnStart);
const cueBlock=s.slice(cueStart,s.indexOf('];',cueStart)+2);
const wrapper=`(()=>{${dataBlock}${cueBlock};return {score,criteria,weaks,items,p3Overall,cuePoints};})()`;
const data=vm.runInNewContext(wrapper,{});
const text=JSON.stringify(data,null,2)+'\n';
const file=path.join(root,'assets/data/speaking_review.json');
if(process.argv.includes('--check'))assert.equal(fs.readFileSync(file,'utf8'),text);
else fs.writeFileSync(file,text);
console.log('Exact fixed speaking review exported (criteria/weaks/p1-p2-p3 items/examiner overall/cue points); fixed demo scores retained, never regraded');
